---
    doc_root: /var/www/public/
    sys_packages: ["nano", "sqlite"]
    dist: xenial
    php_packages: ["php", "libapache2-mod-php", "php-mysql", "php-xml", "php-dev", "php-xdebug", "php-sqlite3", "php-common"]
    pecl_packages: []
